# Generated by Django 4.0.1 on 2023-01-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_contact',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
